name: CI

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches:
            - develop
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    setup:
        name: Setup
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./

    lint:
        name: Run code linter
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./

            - name: Lint
              working-directory: ./
              run: poetry run $(make lint --just-print --silent)

    format:
        name: Run formatter
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./

            - name: Find format differences
              working-directory: ./
              run: poetry run ruff format --diff

    type-check:
        name: Check static types
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./

            - name: Check static types
              working-directory: ./
              run: poetry run $(make type-check --just-print --silent)

    spelling-check:
        name: Run spelling check
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./

            - name: Run spelling check
              working-directory: ./
              run: poetry run $(make spelling-check --just-print --silent)

    test:
        name: Run the tests
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./

            - name: Copy "app.conf.test" to "app.conf"
              working-directory: ./
              run: cp app.conf.test app.conf

            - name: Run the tests
              working-directory: ./
              run: poetry run $(make test-cov-xml --just-print --silent)

            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                name: coverage-mock
                path: ./

    sonar:
        name: SonarCloud
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Download coverage report
              uses: actions/download-artifact@v4
              with:
                name: coverage-mock
                path: ./

            - name: Run SonarCloud scanner
              uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/sonarcloud@main
              with:
                sonar-token: ${{ secrets.SONAR_TOKEN }}
                project-base-dir: ./
